import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  setupSidebar: [{ type: 'autogenerated', dirName: 'setup' }],
  documentationSidebar: [{ type: 'autogenerated', dirName: 'documentation' }],
  snippetsSidebar: [{ type: 'autogenerated', dirName: 'snippets' }],
}

export default sidebars
