export const FEEDS = [
  {
    slug: 'alfred-app',
    title: 'Alfred App - Mac OS X Quicklaunch Application',
    description:
      'Latest entries from Alfred App - Mac OS X Quicklaunch Application.',
    websiteUrl: 'https://www.alfredapp.com/blog/',
    feedUrl: 'http://blog.alfredapp.com/feed/',
    collection: 'alfredAppFeed',
  },
  {
    slug: 'bettertouchtool-blog-posts',
    title: 'Blog Posts - BetterTouchTool Community',
    description: 'Latest entries from Blog Posts - BetterTouchTool Community.',
    websiteUrl: 'https://community.folivora.ai/c/blog-posts/12',
    feedUrl: 'https://community.folivora.ai/c/blog-posts.rss',
    collection: 'betterTouchToolBlogPostsFeed',
  },
  {
    slug: 'commitstrip',
    title: 'CommitStrip',
    description: 'Latest entries from CommitStrip.',
    websiteUrl: 'https://www.commitstrip.com',
    feedUrl: 'https://feeds.feedburner.com/CommitStrip',
    collection: 'commitStripFeed',
  },
  {
    slug: 'emma',
    title: 'Emma',
    description: 'Latest entries from Emma.',
    websiteUrl: 'https://emmaclit.com',
    feedUrl: 'https://emmaclit.com/feed/',
    collection: 'emmaFeed',
  },
  {
    slug: 'ils-abusent-grave',
    title: 'ils abusent grave',
    description: 'Latest entries from ils abusent grave.',
    websiteUrl: 'http://ilsabusentgrave.com',
    feedUrl: 'http://ilsabusentgrave.com/feed',
    collection: 'ilsAbusentGraveFeed',
  },
  {
    slug: 'xkcd',
    title: 'xkcd',
    description: 'Latest entries from xkcd.',
    websiteUrl: 'https://xkcd.com/',
    feedUrl: 'http://xkcd.com/rss.xml',
    collection: 'xkcdFeed',
  },
  {
    slug: 'javascriptweekly',
    title: 'JavaScript Weekly',
    description: 'Latest entries from JavaScript Weekly.',
    websiteUrl: 'https://javascriptweekly.com/',
    feedUrl: 'http://javascriptweekly.com/rss',
    collection: 'javascriptWeeklyFeed',
  },
  {
    slug: 'wes-bos',
    title: 'Wes Bos',
    description: 'Latest entries from Wes Bos.',
    websiteUrl: 'https://wesbos.com',
    feedUrl: 'https://feeds.simplecast.com/54nAGcIl',
    collection: 'wesBosFeed',
  },
  {
    slug: 'modern-css-solutions',
    title: 'Modern CSS Solutions',
    description: 'Latest entries from Modern CSS Solutions.',
    websiteUrl: 'https://moderncss.dev',
    feedUrl: 'https://moderncss.dev/feed/',
    collection: 'modernCssSolutionsFeed',
  },
  {
    slug: 'marks-dev-blog',
    title: "Mark's Dev Blog",
    description: "Latest entries from Mark's Dev Blog.",
    websiteUrl: 'https://blog.isquaredsoftware.com/index.xml',
    feedUrl: 'https://blog.isquaredsoftware.com/index.xml',
    collection: 'marksDevBlogFeed',
  },
  {
    slug: 'lea-verou-blog',
    title: "Lea Verou's blog",
    description: "Latest entries from Lea Verou's blog.",
    websiteUrl: 'https://lea.verou.me/',
    feedUrl: 'http://feeds2.feedburner.com/leaverou',
    collection: 'leaVerouBlogFeed',
  },
  {
    slug: 'overreacted',
    title: 'overreacted - A blog by Dan Abramov',
    description: 'Latest entries from overreacted - A blog by Dan Abramov.',
    websiteUrl: 'https://overreacted.io/',
    feedUrl: 'https://overreacted.io/rss.xml',
    collection: 'overReactedFeed',
  },
  {
    slug: 'react',
    title: 'React',
    description: 'Latest entries from React.',
    websiteUrl: 'https://reactjs.org',
    feedUrl: 'http://facebook.github.io/react/feed.xml',
    collection: 'reactFeed',
  },
  {
    slug: 'this-week-in-react',
    title: 'This Week In React - Newsletter',
    description: 'Latest entries from This Week In React - Newsletter.',
    websiteUrl: 'https://thisweekinreact.com/newsletter',
    feedUrl: 'https://thisweekinreact.com/newsletter/rss.xml',
    collection: 'thisWeekInReactFeed',
  },
  {
    slug: 'web-dev-simplified',
    title: 'Web Dev Simplified Blog',
    description: 'Latest entries from Web Dev Simplified Blog.',
    websiteUrl: 'https://blog.webdevsimplified.com/',
    feedUrl: 'https://blog.webdevsimplified.com/rss.xml',
    collection: 'webDevSimplifiedFeed',
  },
  {
    slug: 'total-typescript',
    title: 'Total TypeScript',
    description: 'Latest entries from Total TypeScript.',
    websiteUrl: 'https://www.totaltypescript.com',
    feedUrl: 'https://www.totaltypescript.com/rss.xml',
    collection: 'totalTypeScriptFeed',
  },
  {
    slug: 'dawntraoz-blog',
    title: "Dawntraoz's blog",
    description: "Latest entries from Dawntraoz's blog.",
    websiteUrl: 'https://dawntraoz.com/feed.xml',
    feedUrl: 'https://www.dawntraoz.com/feed.xml',
    collection: 'dawntraozBlogFeed',
  },
  {
    slug: 'kent-c-dodds-blog',
    title: 'Kent C. Dodds Blog',
    description: 'Latest entries from Kent C. Dodds Blog.',
    websiteUrl: 'https://kentcdodds.com/blog',
    feedUrl: 'https://kentcdodds.com/blog/rss.xml',
    collection: 'kentCDoddsBlogFeed',
  },
  {
    slug: 'josh-comeau-blog',
    title: "Josh Comeau's blog",
    description: "Latest entries from Josh Comeau's blog.",
    websiteUrl: 'https://www.joshwcomeau.com/',
    feedUrl: 'https://www.joshwcomeau.com/rss.xml',
    collection: 'joshComeauBlogFeed',
  },
  {
    slug: 'thirty-seconds-of-code',
    title: '30 seconds of code',
    description: 'Latest entries from 30 seconds of code.',
    websiteUrl: 'https://www.30secondsofcode.org',
    feedUrl: 'https://www.30secondsofcode.org/feed',
    collection: 'thirtySecondsOfCodeFeed',
  },
  {
    slug: 'colinhacks',
    title: 'Colin McDonnell @colinhacks',
    description: 'Latest entries from Colin McDonnell @colinhacks.',
    websiteUrl: 'https://colinhacks.com',
    feedUrl: 'https://colinhacks.com/rss.xml',
    collection: 'colinHacksFeed',
  },
  {
    slug: 'esif',
    title: 'Educational Sensational Inspirational Foundational',
    description:
      'Latest entries from Educational Sensational Inspirational Foundational.',
    websiteUrl: 'https://esif.dev/',
    feedUrl: 'https://esif.dev/feed.xml',
    collection: 'esifFeed',
  },
  {
    slug: 'robin-wieruch',
    title: 'Robin Wieruch',
    description: 'Latest entries from Robin Wieruch.',
    websiteUrl: 'https://www.robinwieruch.de/',
    feedUrl: 'https://www.robinwieruch.de/index.xml',
    collection: 'robinWieruchFeed',
  },
  {
    slug: 'deno',
    title: 'Deno',
    description: 'Latest entries from Deno.',
    websiteUrl: 'https://deno.com/blog',
    feedUrl: 'https://deno.com/feed',
    collection: 'denoFeed',
  },
  {
    slug: 'sindre-sorhus-blog',
    title: 'Sindre Sorhus - Blog',
    description: 'Latest entries from Sindre Sorhus - Blog.',
    websiteUrl: 'https://sindresorhus.com',
    feedUrl: 'https://sindresorhus.com/rss.xml',
    collection: 'sindreSorhusBlogFeed',
  },
  {
    slug: 'html-css-tip-of-the-week',
    title: 'HTML & CSS Tip of the Week',
    description: 'Latest entries from HTML & CSS Tip of the Week.',
    websiteUrl: 'https://html-css-tip-of-the-week.netlify.app/',
    feedUrl: 'https://html-css-tip-of-the-week.netlify.app/rss.xml',
    collection: 'htmlCssTipOfTheWeekFeed',
  },
  {
    slug: 'ahmad-shadeed',
    title: 'Ahmad Shadeed',
    description: 'Latest entries from Ahmad Shadeed.',
    websiteUrl: 'https://ishadeed.com/',
    feedUrl: 'https://ishadeed.com/feed.xml',
    collection: 'ahmadShadeedFeed',
  },
  {
    slug: 'phil-nash',
    title: 'Phil Nash',
    description: 'Latest entries from Phil Nash.',
    websiteUrl: 'https://philna.sh/',
    feedUrl: 'https://philna.sh/feed.xml',
    collection: 'philNashFeed',
  },
  {
    slug: 'piccalilli-css',
    title: 'Piccalilli - CSS topic archive',
    description: 'Latest entries from Piccalilli - CSS topic archive.',
    websiteUrl: 'https://piccalil.li/',
    feedUrl: 'https://piccalil.li/category/css.xml',
    collection: 'piccalilliCssFeed',
  },
  {
    slug: 'every-layout-blog',
    title: 'The Every Layout Blog',
    description: 'Latest entries from The Every Layout Blog.',
    websiteUrl: 'https://every-layout.dev',
    feedUrl: 'https://every-layout.dev/feed.xml',
    collection: 'everyLayoutBlogFeed',
  },
  {
    slug: 'cassidy-williams',
    title: 'Cassidy Williams',
    description: 'Latest entries from Cassidy Williams.',
    websiteUrl: 'https://cassidoo.co/',
    feedUrl: 'https://cassidoo.co/rss.xml',
    collection: 'cassidyWilliamsFeed',
  },
  {
    slug: 'kettanaito',
    title: 'kettanaito.com',
    description: 'Latest entries from kettanaito.com.',
    websiteUrl: 'https://kettanaito.com',
    feedUrl: 'https://kettanaito.com/blog/rss.xml',
    collection: 'kettanaitoFeed',
  },
  {
    slug: 'developer-way',
    title: 'Developer Way',
    description: 'Latest entries from Developer Way.',
    websiteUrl: 'https://www.developerway.com',
    feedUrl: 'https://www.developerway.com/rss.xml',
    collection: 'developerWayFeed',
  },
  {
    slug: 'wizard-zines',
    title: 'Wizard Zines',
    description: 'Latest entries from Wizard Zines.',
    websiteUrl: 'https://wizardzines.com',
    feedUrl: 'https://wizardzines.com/index.xml',
    collection: 'wizardZinesFeed',
  },
  {
    slug: 'adam-argyle',
    title: 'Adam Argyle',
    description: 'Latest entries from Adam Argyle.',
    websiteUrl: 'https://nerdy.dev',
    feedUrl: 'https://nerdy.dev/rss',
    collection: 'adamArgyleFeed',
  },
  {
    slug: 'thatshubham-blog',
    title: 'Blog - thatshubham',
    description: 'Latest entries from Blog - thatshubham.',
    websiteUrl: 'https://thatshubham.com/blog',
    feedUrl: 'https://thatshubham.com/rss.xml',
    collection: 'thatshubhamBlogFeed',
  },
] as const

export const JAVASCRIPT_WEEKLY_FEED = FEEDS.find(
  feed => feed.slug === 'javascriptweekly',
)!

export type FeedDefinition = (typeof FEEDS)[number]

export function getFeedBySlug(slug: string): FeedDefinition | undefined {
  return FEEDS.find(feed => feed.slug === slug)
}
